apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: p3cival/backend:latest
          ports:
            - containerPort: 9000
          env:
            - name: 'REDIS_DNS'
              value: redis