apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - nodePort: 30023
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
