name: deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
steps: 
  - name: Checkout
    uses: actions/checkout@v2
    run: echo ${{inputs.environment}}