name: deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
jobs:
  deploy_front:
    runs-on: ubuntu-latest
    steps: 
    - name: Download code
      uses: actions/download-artifact@v3
      with: 
        name: frontend
        path: .
    - name: Build Docker
      run: chmod +x workflows/ci/build-docker.sh && workflows/ci/build-docker.sh 
    - name: Push Docker
      run: chmod +x workflows/ci/push-docker.sh && workflows/ci/push-docker.sh 

  deploy_backend:
    runs-on: ubuntu-latest
    steps: 
    - name: Download code
      uses: actions/download-artifact@v3
      with: 
        name: backend
        path: .
    - name: Build Docker
      run: chmod +x workflows/ci/build-docker.sh && workflows/ci/build-docker.sh 
    - name: Push Docker
      run: chmod +x workflows/ci/push-docker.sh && workflows/ci/push-docker.sh 