name: deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
jobs:
  deploy_front:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: simple_fortune_cookie:latest

  deploy_backend:
    runs-on: ubuntu-latest
    steps: 
    - name: Download code
      uses: actions/download-artifact@v3
      with: 
        name: backend
        path: .
    - name: Build Docker
      run: chmod +x ./.github/workflows/ci/build-docker.sh && ./.github/workflows/ci/build-docker.sh 
    - name: Push Docker
      run: chmod +x ./.github/workflows/ci/push-docker.sh && ./.github/workflows/ci/push-docker.sh 
