name: deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Echo varaiable
      run: echo ${{inputs.environment}}