name: Go CI Template

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Build Frontend
      run: |
        go build -o frontend ./...
        cp ../../Dockerfile .
      working-directory: ./Docker/Frontend/frontend
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: .
    
    - name: Build Backend
      run: |
        go build -o backend ./...
        cp ../../Dockerfile .
      working-directory: ./Docker/Backend/backend
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: backend
        path: ./Docker/Backend/backend

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Test Frontend
      run: go test ./...
      working-directory: ./Docker/Frontend/frontend

