name: kuber-deploy

on:
  workflow_call:

jobs:
  deploy_kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Copy kubeconfig
        working-directory: ./kubernetes
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: run frontend
        working-directory: ./kubernetes
        run: kubectl --kubeconfig kubeconfig apply -f .
        
        
