name: main

on: [push]

jobs:
  build:
    uses: ./.github/workflows/go.yml

  deployDev: 
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/issue/')
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: 'development'
      docker_username: ${{github.actor}}
      docker_password: ${{secrets.GITHUB_TOKEN}}
      GIT_COMMIT: ${{ github.ref }}

  deployStage:
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/development') 
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: 'staging'
      docker_username: ${{github.actor}}
      docker_password: ${{secrets.GITHUB_TOKEN}}
      GIT_COMMIT: ${{ github.ref }}

  deployProd:
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/main')
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: 'production'
      docker_username: ${{github.actor}}
      docker_password: ${{secrets.GITHUB_TOKEN}}
      GIT_COMMIT: ${{ github.ref }}
