name: main

on: [push]

jobs:
  build:
    uses: ./.github/workflows/go.yml

  Docker_Dev: 
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/issue/')
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: 'development'
      version: 'beta'
    secrets: inherit

  Docker_Stag:
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/development') 
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: 'staging'
      version: 'alpha'
    secrets: inherit

  Docker_Prod:
    needs: [build]
    if: startsWith(github.ref, 'refs/heads/main')
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: 'production'
      version: 'latest'
    secrets: inherit
    

  Kubernetes_Stag:
    needs: [Docker_Stag]
    uses: ./.github/workflows/kubeDeploy.yaml
    secrets: inherit
    with:
      version: 'alpha'
  
  Kub_Dev:
    #needs: [Docker_Dev]
    uses: ./.github/workflows/kubeDeploy.yaml
    secrets: inherit
    with:
      version: 'beta'
  
  Kub_Prod:
    needs: [Docker_Prod]
    uses: ./.github/workflows/kubeDeploy.yaml
    secrets: inherit
    with:
      version: 'latest'

  Testing:
    runs-on: ubuntu-latest
    needs: [Kub_Dev]
    steps:
    - name: Download Code
      uses: actions/checkout@v3
      with:
        name: code
        path: .
    - name: Execute Curl test
      run: bash ci/curl-test.sh


